resources:
  - name: myResource
    type: PropertyBag
    configuration:
      endTime: 0

pipelines:
  - name: myPipeline
    steps:
      - name: input1
        type: Bash
        configuration:
          outputResources:
            - name: myResource
        execution:
          onExecute:
            - write_output myResource endTime=${run_created_at}
            - echo "test"
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: myResource
              newVersionOnly: true
        execution:
          onExecute:
            - echo "test"
      - name: step2
        type: Bash
        configuration:
          inputResources:
            - name: myResource
        execution:
          onExecute:
            - echo "test"
