resources:
  - name: myResource
    type: PropertyBag
    configuration:
      Version: ""
pipelines:
  - name: myPipeline
    steps:
      - name: input1
        type: Bash
        configuration:
          outputResources:
            - name: myResource
        execution:
          onExecute:
            - write_output myResource startTime=${run_created_at}
            - add_pipeline_variables startTime=${run_created_at}
            - echo "test"
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: myResource
              newVersionOnly: true
        execution:
          onExecute:
            - echo "test"
      - name: step2
        type: Bash
        configuration:
          inputResources:
            - name: myResource
        execution:
          onExecute:
            - echo "test"
