resources:
  - name: myResource
    type: PropertyBag
    configuration:
      Version: "1.54.2"
pipelines:
  - name: myPipeline
    steps:
      - name: input1
        type: Bash
        configuration:
          outputResources:
            - name: myResource
        execution:
          onExecute:
            #- write_output myResource endTime=${run_created_at}
            #- write_output myResource startTime=${startTime}
            - echo "{\"startTime\":\"${run_created_at}\"}" > myFile.json
            - echo "test"
            - add_pipelines_files myFile.json myResource
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: myResource
              newVersionOnly: true
        execution:
          onExecute:
            - echo "test"
            - restore_pipelines_files myResource
            - cat myResource
      - name: step2
        type: Bash
        configuration:
          inputResources:
            - name: myResource
        execution:
          onExecute:
            - echo "test"
