resources:
  - name: {{ .Values.namePrefix }}_bag
    type: PropertyBag
    configuration:
      releaseVersion: ""

pipelines:
  - name: hello_world
    steps:
      - name: first
        type: Bash
        execution:
          onExecute:
            - Echo "hello"
      - name: second
        type: Bash
        execution:
          onExecute:
            - echo "Hello World"
