resources:
  - name: {{ .Values.namePrefix }}_bag
    type: PropertyBag
    configuration:
      releaseVersion: ""
      chronological: true

pipelines:
  - name: hello_world
    steps:
      - name: first
        type: Bash
        execution:
          onExecute:
            - echo "hello"
      - name: second
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "Hello World"
