resources:
  - name: myAqlResource
    type: Aql
    configuration:
      
  - name: myReleaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDistributionIntegration
      name: name
      version: '1'

pipelines:
  - name: pipelineToUpdateResource
    steps:
      - name: myBashStep
        type: Bash
        configuration:
          integrations:
            - name: myArtifactoryIntegration
          outputResources:
            - name: myAqlResource
        execution:
          onExecute:
            - write_output myAqlResource query='hello'

  - name: CreateReleaseBundlePipeline
    configuration:
      inputResources:
        - name: myAqlResource
      outputResources:
        - name: myReleaseBundle
    steps:
      - name: myCreateReleaseBundleStep
        type: CreateReleaseBundle
        configuration:
          
