resources:  
  - name: Image_1
    type: Image 
    configuration:         
      registry:            
      imageName:              
      imageTag: 

pipelines:
  - name: pipelines_Image_1
    steps:
      - name: step_Image_1
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: 
        execution:
          onExecute:
            - write_output "executing step..."
            
